# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_cliente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='DD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Generica', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('unidad', models.CharField(choices=[('Mb', 'Mb'), ('Gb', 'Gb'), ('Tb', 'Tb')], default='Gb', max_length=2)),
                ('serial', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Memoria Ram',
                'verbose_name_plural': 'Memorias Ram',
            },
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('dd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.DD')),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Generica', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('unidad', models.CharField(choices=[('Mb', 'Mb'), ('Gb', 'Gb'), ('Tb', 'Tb')], default='Gb', max_length=2)),
                ('serial', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Memoria Ram',
                'verbose_name_plural': 'Memorias Ram',
            },
        ),
        migrations.AddField(
            model_name='desktop',
            name='ram',
            field=models.ManyToManyField(to='pc.ram'),
        ),
    ]
