# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dispositivo Adicional',
                'verbose_name_plural': 'Dispositivos Adicionales',
            },
        ),
        migrations.CreateModel(
            name='CdRom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Generica', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('unidad', models.CharField(choices=[('Mb', 'Mb'), ('Gb', 'Gb'), ('Tb', 'Tb')], default='Gb', max_length=2)),
                ('serial', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'CD-ROM',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], default='INTEL', max_length=50)),
                ('unidad', models.CharField(choices=[('Mhz', 'Mhz'), ('Ghz', 'Ghz')], default='Ghz', max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('socket', models.CharField(default='775', max_length=50)),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Fuente de Poder',
                'verbose_name_plural': 'Fuentes de Poder',
            },
        ),
        migrations.CreateModel(
            name='MoBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Tarjeta Madre',
                'verbose_name_plural': 'Tarjetas Madre',
            },
        ),
        migrations.AlterModelOptions(
            name='dd',
            options={'verbose_name': 'Disco Duro', 'verbose_name_plural': 'Discos Duros'},
        ),
        migrations.AlterModelOptions(
            name='desktop',
            options={'verbose_name': 'Computadora', 'verbose_name_plural': 'Computadoras'},
        ),
        migrations.RemoveField(
            model_name='dd',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='ram',
        ),
        migrations.AddField(
            model_name='desktop',
            name='am',
            field=models.ManyToManyField(to='pc.Ram'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='detalles',
            field=models.TextField(default='Ninguna'),
        ),
        migrations.AlterField(
            model_name='dd',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dd',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dd',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='desktop',
            name='dd',
        ),
        migrations.AddField(
            model_name='desktop',
            name='dd',
            field=models.ManyToManyField(to='pc.DD'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='adicional',
            field=models.ManyToManyField(to='pc.Adicional'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='cdRom',
            field=models.ManyToManyField(to='pc.CdRom'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='cpu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pc.Cpu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desktop',
            name='fuente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pc.Fuente'),
            preserve_default=False,
        ),
    ]
