# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_auto_20160615_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='am',
            field=models.ManyToManyField(to='pc.Ram'),
        ),
    ]
