# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0005_auto_20160616_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='adicional',
            field=models.ManyToManyField(to='pc.Adicional', verbose_name='Dispositivos Adicionales'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='am',
            field=models.ManyToManyField(to='pc.Ram', verbose_name='Memorias Ram'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='cdRom',
            field=models.ManyToManyField(to='pc.CdRom', verbose_name='Quemadoras'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Cpu', verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='dd',
            field=models.ManyToManyField(to='pc.DD', verbose_name='Discos Duros'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Fuente', verbose_name='Fuente de Poder'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='moBo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.MoBo', verbose_name='Tarjeta Madre'),
        ),
    ]
