# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0006_auto_20160622_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdrom',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='cdrom',
            name='capacidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cdrom',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cdrom',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='am',
            field=models.ManyToManyField(to='pc.Ram', verbose_name='Memorias Ram'),
        ),
    ]
