# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0013_auto_20160720_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='am',
            new_name='ram',
        ),
        migrations.AlterField(
            model_name='desktop',
            name='ram',
            field=models.ManyToManyField(to='pc.Ram', verbose_name='Memorias Ram'),
        ),
    ]
