# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0014_auto_20160720_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='modelo',
            field=models.CharField(default='Core 2 Duo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desktop',
            name='ram',
            field=models.ManyToManyField(to='pc.Ram', verbose_name='Memorias Ram'),
        ),
    ]
