# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0015_auto_20160720_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='bolso',
        ),
        migrations.AlterField(
            model_name='desktop',
            name='ram',
            field=models.ManyToManyField(to='pc.Ram', verbose_name='Memorias Ram'),
        ),
    ]
