# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
