# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0004_auto_20160615_1536'),
        ('cliente', '0004_cliente_usuario'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'verbose_name': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Servicio_Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(blank=True)),
                ('abono', models.PositiveSmallIntegerField(blank=True)),
                ('cancelado', models.BooleanField()),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True)),
                ('fecha_entrega', models.DateField(blank=True)),
                ('observaciones', models.TextField(default='Ninguna')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Desktop')),
                ('servicios', models.ManyToManyField(to='main.Servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios Tecnicos',
                'verbose_name': 'Servicio Tecnico',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('prefijo_telefono', models.CharField(choices=[('0412', '0412'), ('0426', '0426'), ('0416', '0416'), ('0424', '0424')], max_length=50)),
                ('telefono', models.CharField(max_length=7)),
                ('usuario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicio_tecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tecnico'),
        ),
    ]
