# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160615_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
