# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160717_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='abono',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio_tecnico',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
