# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20160622_2033'),
        ('pc', '0011_auto_20160719_2156'),
        ('main', '0004_auto_20160718_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_Tecnico_Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveSmallIntegerField(blank=True)),
                ('abono', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cancelado', models.BooleanField()),
                ('fecha_recepcion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(default='Ninguna')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Laptop')),
                ('servicios', models.ManyToManyField(to='main.Servicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tecnico')),
            ],
            options={
                'verbose_name': 'Servicio Tecnico',
                'verbose_name_plural': 'Servicios Tecnicos',
            },
        ),
        migrations.RenameModel(
            old_name='Servicio_Tecnico',
            new_name='Servicio_Tecnico_Desktop',
        ),
    ]
