# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160719_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio_tecnico_desktop',
            options={'verbose_name': 'Servicio Tecnico PC', 'verbose_name_plural': 'Servicios Tecnicos PCs'},
        ),
        migrations.AlterModelOptions(
            name='servicio_tecnico_laptop',
            options={'verbose_name': 'Servicio Tecnico Laptop', 'verbose_name_plural': 'Servicios Tecnicos Laptops'},
        ),
    ]
